name: Go CI

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: helm-check-auth-server
        uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts/auth-server
          CHART_VALUES: ./charts/auth-server/values.yaml
      - name: helm-check-time-server
        uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: ./charts/time-server
          CHART_VALUES: ./charts/time-server/values.yaml
